name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 172.166.192.99 >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no chef@172.166.192.99 "echo SSH connection successful"

      - name: Deploy to Azure VM
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no chef@172.166.192.99 << 'EOF'
            set -e  # Exit on error
            echo "🔹 Connecting to Azure VM and deploying..."

            # Ensure deployment directory exists
            mkdir -p /home/chef/fastapi-book-project
            cd /home/chef/fastapi-book-project

            # Clone or update repository
            if [ -d ".git" ]; then
              echo "📥 Pulling latest changes..."
              git reset --hard  # Reset any local changes
              git pull origin main
            else
              echo "🚀 Cloning repository..."
              git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/Eben-DevOps/fastapi-book-project.git .
            fi

            # Stop running containers
            echo "🛑 Stopping existing containers..."
            docker-compose down

            # Clean up old images, networks, and volumes
            echo "🧹 Cleaning up old Docker images..."
            docker system prune -a -f

            # Pull latest images
            echo "📦 Pulling latest Docker images..."
            docker-compose pull

            # Rebuild and restart containers
            echo "🔄 Restarting application..."
            docker-compose up --force-recreate --build -d

            echo "✅ Deployment completed!"
          EOF